### PR TITLE
AsciiDoc Parser support

### PR DESCRIPTION
**Pull request by gerryhocks**
These additions utilize the Ruby parser from the AsciiDoctor project to provide RedPen with basic validation of the none-markup elements of a user's AsciiDoc documents.

It includes updates to the web demo GUI to demonstrate AsciiDoc support.

There is a small issue with offset calculations for the end position of errors when the error is towards the end of an inline element or the end of a sentence, but this issue is caused by how RedPen calculates the end position of errors - we should review that.

### CODE REVIEW

**Comment by takahi-i** [comment]
Thank you very much for the excellent work as always @gerryhocks!

**Comment by takahi-i** [comment]
Ref #432

**Comment by mojavelinux** [comment]
I just tried it out and my first thought is that tool like this is definitely going to fill an important void in the AsciiDoc ecosystem. So nice work!

It would be helpful if you itemized what validations are enforced that are unique to AsciiDoc so that testers know what to look for. I'm assuming that a lot of the work in the initial pull request is just to get the RedPen analyzer to be able to work within (and honor) the structure of an AsciiDoc document.

Perhaps we can start a list somewhere of validations so that we know what we're shooting for. Here are just a couple I can think of:

1. Validate that a xref points to a valid target
2. Validate that a delimited block has matching boundaries (delimiter lines are of equal length)
3. Level-0 sections (after the doctitle) are only present if the doctype is book
4. Validate that an attribute reference points (e.g., `{foobar}`) to a defined attribute (`foobar`)

...and there are plenty more.

**Comment by takahi-i** [comment]
Thank you very much for the valuable comments ＠mojavelinux!

Right! This pull request is for checking the contents of AsciiDoc documents not the format AsciiDoc styles. This is because RedPen project has focused on the validation for the text within the markup and the model structure (Document model) which is extracted by parsers is relatively simple and applicable to any data formats (see http://redpen.cc/docs/latest/extend.html#model-structure).

But I understand that reporting such formatting issues are valuable for RedPen and AsciiDoc users. RedPen team members will discuss whether RedPen should support the validation of the markup itself or when we should support it after the v1.3 release.

This pull request itself is merged with the basic AsciiDoc support is satisfied, which is included v1.3.

**Comment by mojavelinux** [comment]
Cool! Thanks for the insight!

**Comment by takahi-i** [comment]
LGTM

**Pull request merged**
