### PR TITLE
Updates to RedPen demonstation web page

### PR DESCRIPTION
**Pull request by gerryhocks**
Changes to the demonstration web page. Specifically:

redpen-server - Demonstration web page:
* Selected a bootstrap theme more sympathetic with the redpen.cc site
* Added menu and edited some page friendly logos
* Added cheap preliminary automatic-language-detection and simplified the buttons for the page
* Moved page-specific javascript into the page (temporarily) and started the formation of an initial redpen js object in redpen.js
* Added placeholders for future manipulation of the active redpen features via the demo page. Currently this is read-only.
* Added some sample english and japanese text (just copied from the redpen.cc site)
* Update redpen.js to include new configuration API call
* Added menu link to show the server API page

redpen-server - REST API:
* Added a small Wink API describer (from previous Wink dabblings) to provide a page that automatically describes the API
* Added a config/redpen API call to retrieve the active RedPen configurations

redpen-core:
* Added getters to RedPen to enable external access to the particular configuration of a RedPen instance

### CODE REVIEW

**Comment by takahi-i** [comment]
Thanks a lot!

**Comment by gerryhocks** [comment]
I've made the changes you recommended. I also updated the English sample text to match the sample document from the project.

**Comment by takahi-i** [comment]
LGTM

**Comment by takahi-i** [comment]
Thank you very much @gerryhocks!

**Pull request merged**
