### PR TITLE
User friendly input/output help

### PR DESCRIPTION
**Pull request by kenhys**
Show supported input/output format in help string.

http://redpen.cc/docs/latest/format.html
http://redpen.cc/docs/latest/output.html

### CODE REVIEW

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
Thank you very much for the contribution!

Can you grant these changes under the Apache License 2.0 @kenhys?

**Comment by kenhys** [comment]
Sure! I'm intended it.

**Comment by takahi-i** [comment]
LGTM

**Comment by takahi-i** [comment]
Thank you very much!

**Pull request merged**
