### PR TITLE
make validation process thread-safe

### PR DESCRIPTION
**Pull request by yusuke**
instantiate or clone validators everytime to validation process thread-safe

### CODE REVIEW

**Comment by takahi-i** [comment]
Thank you very much for impressive contribution @yusuke!  I would like to know if ValidatorConfiguration   (https://github.com/recruit-tech/redpen/blob/master/redpen-core/src/main/java/cc/redpen/config/ValidatorConfiguration.java) should override equals and hashCode to RedPen server works with multiple configuration settings before merge.

**Comment by yusuke** [comment]
definitely! I'll fix that along with a test case.

**Comment by takahi-i** [comment]
Great!

**Comment by yusuke** [comment]
I dumped CloneableValidator and implementing a simple caching mechanism to improve those dictionary-based Validators' initialization costs.

**Comment by takahi-i** [comment]
Thank you very much @yusuke! I will look into the change.

**Comment by takahi-i** [comment]
LGTM!

**Pull request merged**
