### PR TITLE
Detect markdown (.md) as input format

### PR DESCRIPTION
**Pull request by kenhys**
Note that default input format (plain) is not changed.

### CODE REVIEW

**Comment by kenhys** [comment]
It is useful that redpen works even if user forget to specify `-f markdown` in command line option for text files which are markdown only.

**Comment by takahi-i** [comment]
:+1:

**Comment by kenhys** [comment]
I agree with following redpen's license about this PR. :smiley:

**Comment by takahi-i** [comment]
Cool feature! Thank you very much @kenhys as always!

**Pull request merged**
