### PR TITLE
redpen-392 output position offset with JSONFormatter

### PR DESCRIPTION
**Pull request by takahi-i**
redpen-392 output position offset with JSONFormatter

### CODE REVIEW

**Comment by gerryhocks** [comment]
I was wondering if we could also include the validator name in the JSON output, as in:

  jsonError.put("validator", error.getValidatorName());

This would help when displaying errors via the web demo.

**Comment by gerryhocks** [comment]
(sorry for the close - I pushed the wrong button :) )

**Comment by takahi-i** [comment]
Thank you a lot for the comment @gerryhocks! I will make modify JSONFormatter to flush the validator names.

**Comment by gerryhocks** [comment]
That looks pretty good :) 

It is a small and unimportant point, but I did notice that the formatted line number is called lineNum, and the method in ValidationError is getLineNumber(), which calls sentence.getLineNum(). Would it be worth in future renaming ValidationError.getLineNumber() to Validation.getLineNum() for consistency?

**Comment by takahi-i** [comment]
Thank you a lot for the comment @gerryhocks! I agree to the method rename for consistency. I change the sentence.getLineNum() to sentence.getLineNumber and did not change the error.getLineNumber() method to keep the consistency with ValidationError.getColumnLineNum**ber**() method.

**Comment by takahi-i** [comment]
If the changes acceptable, I will merge the changes and release v1.1.1

**Comment by gerryhocks** [comment]
Sorry for the late reply - pesky timezones :)
It looks good - nice and consistent !

**Comment by takahi-i** [comment]
Thank you for the review @gerryhocks.

**Pull request merged**
