### PR TITLE
Changes to specify Validator configuration in a web service call

### PR DESCRIPTION
**Pull request by gerryhocks**
* Modified RedPen web server and core to support passing configuration settings with the validation request JSON
* Added new JSON-based validate API call that permits the specification of the language, parser, output format, the enabled validators and their configurations.
* Updated the web GUI to sub-impose the validators under the editor to provide space to add the editable properties
* Added extra tab to show the JSON request’s content
* Implemented server-side processing of JSON configuration and creation of redpen instance
* Updated GUI to send edited properties along with each validate request
* Fixed bug with line number calculation for multiple blank lines in PlainTextParser
* Corrected highlighting and positioning of errors displayed in editor
* Cleaned up GUI to make it more suitable for presentations

### CODE REVIEW

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
Excellent work @gerryhocks! I will merge after I understand the changes. Hopeufully tomorrow..

**Comment by gerryhocks** [comment]
No problem! Let me know if there are any issues.

**Comment by takahi-i** [comment]
Thank you a lot as always!

**Pull request merged**
