### PR TITLE
Version bump to 1.1

### PR DESCRIPTION
**Pull request by akinomurasame**
Align name of the output file with the version of the redpen-cli command.

### CODE REVIEW

**Comment by akinomurasame** [comment]
OMG, Why build failed?

in my environment is not failed.

```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

$ javac -version
javac 1.8.0_25

$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T02:29:23+09:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] redpen
[INFO] redpen-core
[INFO] redpen-cli
[INFO] redpen-server
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building redpen 1.0
[INFO] ------------------------------------------------------------------------

...

[INFO] Reactor Summary:
[INFO]
[INFO] redpen ............................................. SUCCESS [  0.220 s]
[INFO] redpen-core ........................................ SUCCESS [  3.002 s]
[INFO] redpen-cli ......................................... SUCCESS [  3.221 s]
[INFO] redpen-server ...................................... SUCCESS [  3.168 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.713 s
[INFO] Finished at: 2015-01-14T08:37:40+09:00
[INFO] Final Memory: 32M/466M
[INFO] ------------------------------------------------------------------------
````

**Comment by takahi-i** [comment]
Oops! thanks for the report @akinomurasame. I will look into the build failure.

**Comment by akinomurasame** [comment]
@takahi-i Thank you for advice :smile:
I was able to successfully build.

It should be noted that the version of the cc.redpen does not change.
If there even than may be changed, I'll add a commit.

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
Thanks a lot @akinomurasame! Can you also please change the version of redpen package to 1.1?

**Comment by akinomurasame** [comment]
Yes, Sir.

I'll get right on it ;-)

**Comment by akinomurasame** [comment]
@takahi-i I was commit done.
Please check it.

**Comment by takahi-i** [comment]
Thanks a lot @akinomurasame! I verified the changes. Can you please confirm that these changes are licensed under the Apache License 2.0?

**Comment by takahi-i** [comment]
If you are ok, I will merge the changes.

**Comment by akinomurasame** [comment]
Sure! Yes, I can.
Please, merge the changes.

**Comment by takahi-i** [comment]
Thanks @akinomurasame  for your contribution!

**Comment by akinomurasame** [comment]
:+1:

**Pull request merged**
